[program:hub-rabbit-consume]
command=php /app/artisan rabbit:consume hr.events
process_name=%(program_name)s_%(process_num)02d
numprocs=1
autostart=true
autorestart=true
stdout_logfile=/app/storage/logs/rabbit-consume.log
stderr_logfile=/app/storage/logs/rabbit-consume-error.log
stopwaitsecs=3600
priority=999
